#database-rds.c7efacvcm0jo.ap-northeast-2.rds.amazonaws.com
#localhost:3306
spring:
#  datasource:
#    url: jdbc:mysql://${MYSQL_DB_HOST}:3306/${MYSQL_DATABASE}
#    username: ${MYSQL_USER}
#    password: ${MYSQL_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    testWhileIdle: true
#    validationQuery: SELECT 1
#    tomcat.max-wait: 60000


  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false


  datasource:
    url: jdbc:mysql://localhost:3306/movie
    username: wookim
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # datasource:
  #   url: jdbc:mysql://localhost:3306/movie
  #   username: root
  #   password: black159
  #   driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true

KMDB:
  key: 4U6V83F44L7Y8VNLF42B

naver:
  url:
    search:
      movie: https://openapi.naver.com/v1/search/local.json

    client:
      id: 13De2BDkkPwBrZddTNyQ
      secret: 5z043okjEz


movie:
  box:
    key: 38b6115a994d498ad200a534627cf969


  servlet:
    multipart:
      enabled: true
      location: D:\\fileupload
      max-file-size: 10MB
      max-request-size: 30MB

file:
  path: D:\\fileupload

jwt:
  secret:
    testKey
